apiVersion: v1
kind: Service
metadata:
  labels:
    app: wireguard
  name: wireguard
spec:
  ports:
  - port: 51820
    protocol: UDP
    targetPort: 51820
    name: wireguard-udp
  selector:
    app: wireguard
  type: LoadBalancer