kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wireguard-configs-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: wireguard-configs-pv
  storageClassName: ""
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wireguard-lib-modules-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: wireguard-lib-modules-pv
  storageClassName: my-local-storage

