apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wireguard

generatorOptions:
  disableNameSuffixHash: true

resources:
  - wireguard-ns.yaml

secretGenerator:
  - name: wireguard-url
    files:
    - host-url